### ISSUE TITLE
zmbackup not starting

### ISSUE THREAD

**Issue by MKReddy-git** [lucascbeyeler/zmbackup#122]
zmbackup 1.2-version installed succesfully

But when i do zmbackup -v i get error
Mailbox Admin Service is Down or Unavailable - See the logs for more information                                              .
Some errors are found inside the config file. Please fix then and try again late              

All my services are running:
       amavis                  Running
        antispam                Running
        antivirus               Running
        dnscache                Running
        ldap                    Running
        logger                  Running
        mailbox                 Running
        memcached               Running
        mta                     Running
        opendkim                Running
        proxy                   Running
        service webapp          Running
        snmp                    Running
        spell                   Running
        stats                   Running
        zimbra webapp           Running
        zimbraAdmin webapp      Running
        zimlet webapp           Running
        zmconfigd               Running

**Comment by vadonka** [comment]
I have the same issue. zmbackup -f -a user@domain.tld is working but only a few MB data saved then the backup quit. It seems the newest zimbra patch's broke this.

**Comment by ananiasfilho** [comment]
I got a issue like this. The problem was: this server has proxy set.
so, check this:
export|grep -i proxy
if you get return like this:
http_proxy="http://172.16.0.1:808"
then, you have proxy.

to solve:
create a new file as root user:
echo "use_proxy=no" > /opt/zimbra/.wgetrc

now try run zmbackup.
su - zimbra
zmbackup -l
zmbackup -v
zmbackup -f

if it not solve, please, provide us more details about your environment.
