### ISSUE TITLE
Issue while trying to restore mails

### ISSUE THREAD

**Issue by dZZZr** [lucascbeyeler/zmbackup#133]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.12
- Linux Distribution & Version: Ubuntu 18.04.2

##### STEPS TO REPRODUCE
zmbackup -f -d domain.pl
zmbackup -r -ldp full-20190711115424 info@domain.pl
zmbackup -r -m full-20190711115424 info@domain.pl

##### ACTUAL RESULTS
Restore mail process with session full-20190711115424 started at Thu Jul 11 12:32:22 CEST 2019Error during the restore process for account info@domain.pl. Error message below:info@domain.pl:
http: error: ConnectionError: ('Connection aborted.', timeout('The write operation timed out',)) while doing POST request to URL: https://192.168.1.215:7071/home/info@domain.pl/?fmt=tgz
Restore mail process with session full-20190711115424 completed at Thu Jul 11 12:32:54 CEST 2019

First, thanks for Your great work.

The issue occurs when restoring the mailbox. Zmbackup can restore some mails but at some point error occurs. It may be associated with polish national characters in mail title/file name.

I attached mailbox.log where You can find the error message:

2019-07-11 12:32:55,457 WARN  [qtp1258084361-525:https:https://192.168.1.215:7071/home/info@domain.pl/?fmt=tgz] [name=zmbackup@somewhere.pl;mid=297;ip=192.168.1.215;port=48034;] misc - ArchiveFormatter addError:Early EOF: p
ath=Inbox/0000000468-Fwd_ rozliczenie pażdziernik.eml
com.zimbra.cs.service.formatter.FormatterServiceException: Early EOF
ExceptionId:qtp1258084361-525:https:https://192.168.1.215:7071/home/info@domain.pl/?fmt=tgz:1562841175457:aeaea4bb9b567bf4

When I'm using zmmailbox everything is OK.
zmmailbox -z -m info@domain.pl postRestURL "//?fmt=tgz&resolve=skip" /opt/zimbra/backup/full-20190711115424/info@domain.pl.tgz

Best regards,
[mailbox.log](https://github.com/Zmbackup/zmbackup/files/3381752/mailbox.log)

**Comment by ananiasfilho** [comment]
The problem seems be python httpie timeout:
check this file:
**if parallel (multiples restore)**
https://github.com/Zmbackup/zmbackup/blob/d83ab3efbc53d8ef5b20a2742da3fc2661841bb7/project/lib/bash/ParallelAction.sh#L91

**if single account**
https://github.com/Zmbackup/zmbackup/blob/d83ab3efbc53d8ef5b20a2742da3fc2661841bb7/project/lib/bash/RestoreAction.sh#L24

both files have this line on restore funcion:

  ERR=$((http --check-status --verify=no POST "$WEBPROTO://$MAILHOST:7071/home/$2/?fmt=tgz"\

try change it to

ERR=$((http --check-status --timeout 600 --verify=no POST "$WEBPROTO://$MAILHOST:7071/home/$2/?fmt=tgz"\

the option --timeout 600 (is to set timeout to 600s/10minute) if timeout continue, try a high value like 1800 (30 minutes) if backup size is big like 20-30 GB.

Please, give us a feedback about it!

**Comment by lucascbeyeler** [comment]
Fixed - dropped httpie in favor of cURL
