### ISSUE TITLE
PID file

### ISSUE THREAD

**Issue by antonzhelyazkov** [lucascbeyeler/zmbackup#22]
Hi,

It is great that you develop zimbra backup system. I have several recommendations:

1. Add PID file creation while script is running
2. Could you add option to transfer older files to remote location via FTP?

**Comment by lucascbeyeler** [comment]
Hello @antonzhelyazkov,

Thanks for the return. The first one is simple to implement and I think in this weekend I release a new version with this feature. The problem is the second one: This one will take sometime to complete, as I need to change some parts to send the files via FTP. When both are working I answer this issue.

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment]
Hello @antonzhelyazkov,

Sorry for the delay, but the PID file you asked is working in the release 1.1.0. Can you please test and give me some feedback? I will wait for your return.

Regards,
Lucas Costa Beyeler

**Comment by antonzhelyazkov** [comment]
Thanks,

It seems works correct.
I have another issue. I'll open a new issue.
